deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
env:
  matrix:
    secure: z92dFaeXBZMtNaVEbPJJNZtBvbPjfGU5DY8KjqfyCSOQyd04QeX+5kytRnZ9NlQgpbaiKefAGQKmrcdLFW/ppH6iahgPpZBO0o1XWrReBHYiBOOphCZYAwotnwlVD1lfeNwJaRKDnNl5kZd271hC9ipNVSYqbAvfv2dJmhoBCmJ1L1mGVwtkEGQpHakNTrxOYO1WHjxPHyc7FFDjORWHBEwIk3U8pYQbMNxZu1HJjjZW1br5Uad3XVL53nLfxEG34mvFWXSq25F+nDgpO5HeKwaqyk8IpnBmlF3qCXp/JULzpxNRbFiu3AF+oJ0r+AygtUCCUe4AhlziyxVaWvnRQR2TkFiSevo8iFzVwpOfZ+ECRYHphfG9pbaowIoCkxOkBP6MufLrWJDq1Uou0Yp+AQOYBIGNLOYmeNarFOvPoH2z0LY8/KWT7A5IhL7AHpR33TlJ0oibeOs2WknTMWlCVmrZMXAO0J/kMvgnnUcL2PzQ5WaE4R7KL/FhJLDcbL/HeboJ84SyGPvBpZge8Ei2Fw5PZXOD4Q8Za0b8LX53EaTgQ5M+ALDYvkbm+xgdiQabKN6CVHmbZcCKlrYwDypSnSqWAfgznurm7FgTsrPSWT4mfj7k6QcBq5ZJuRjZXaCFOGdrwvHzc79gPxA0F9Ijs0XT7CNuSZLAjZ7nG7jY370=
